### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by hyjun0407** [junron/auto-enum#1]
Traceback (most recent call last):
  File "C:\redacted\python\3\ida_idaapi.py", line 577, in IDAPython_ExecScript
    exec(code, g)
  File "C:/redacted/plugins/auto_enum.py", line 168, in <module>
    class FunctionMap:
  File "C:/redacted/plugins/auto_enum.py", line 195, in FunctionMap
    def expand_enum(self, enum: dict[str, int], enum_id: str) -> dict[str, int]:
TypeError: 'type' object is not subscriptable

Error Occured.

**Comment by junron** [comment]
Please use Python 3.9 or newer: https://stackoverflow.com/a/75202688

**Comment by junron** [comment]
Should be fixed with https://github.com/junron/auto-enum/commit/ac26373f2fea5138b9545b40b5c09e9c3f4b5ccc
