### ISSUE TITLE
Action 'AutoEnum:2232721770192' failed to activate. Traceback:

### ISSUE THREAD

**Issue by maskelihileci** [junron/auto-enum#4]
Dude am I doing something wrong?
I am getting the following error.

Action 'AutoEnum:2232721770192' failed to activate. Traceback:
Traceback (most recent call last):
  File "G:\Dos/IDA Professional 9.0/plugins\enumlib\ui_plugins\ida_plugin.py", line 148, in callback
    ea = next(ida_funcs.get_func(ea).addresses())
AttributeError: 'NoneType' object has no attribute 'addresses'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\Dos/IDA Professional 9.0/plugins\enumlib\ui_plugins\ida_plugin.py", line 111, in activate
    self._activate(ctx)
  File "G:\Dos/IDA Professional 9.0/plugins\enumlib\ui_plugins\ida_plugin.py", line 222, in _activate
    main()
  File "G:\Dos/IDA Professional 9.0/plugins\enumlib\ui_plugins\ida_plugin.py", line 267, in main
    get_imports(library_calls, library_addr)
  File "G:\Dos/IDA Professional 9.0/plugins\enumlib\ui_plugins\ida_plugin.py", line 171, in get_imports
    idaapi.enum_import_names(i, import_names_callback)
  File "G:\Dos\IDA Professional 9.0\python\3\ida_nalt.py", line 3797, in enum_import_names
    return _ida_nalt.enum_import_names(mod_index, py_cb)
SystemError: <built-in function enum_import_names> returned a result with an exception set

**Comment by junron** [comment]
Should be fixed in https://github.com/junron/auto-enum/commit/780517d8cdd0eb8c0bb8191cd676ec2dc1339f92.

**Comment by maskelihileci** [comment]
Problem solved, thanks for the plugin.
